### PR TITLE
refactor: adapt to 2.0 vision

### PR DESCRIPTION
**Pull request by cristianmtr**
Cookie cutter for Executors, for Jina 2.0

- README
- tests
- basic code
- Dockerfile

Closes https://github.com/jina-ai/jina/issues/2761

### CODE REVIEW

**Comment by nan-wang** [comment]
I suggest delivering a minimal working template in the cookie-cutter because the users are mainly community members. It is not necessary to include the following part,
- setup.py
- .github
- tests

**Review by nan-wang — CHANGES_REQUESTED** [review]
The cookiecutter will be shipped together with `Jina` CLI and used by the community members. Therefore, we only ship a minimal template.

**Comment by cristianmtr** [comment]
> I suggest delivering a minimal working template in the cookie-cutter because the users are mainly community members. It is not necessary to include the following part,
> 
> * setup.py
> * .github
> * tests

Got it. 

What about the README? 

We are showing some use cases that the users might not know how to use. The README doesn't say how to push to Hubble, for example. Do we have a cookbook for that, so I can include a part of it?

I also think tests are nice to add, since they verify that the MWU created by cookiecutter actually works.

**Review by nan-wang — CHANGES_REQUESTED** [review]
Made a PR at #9

**Review by nan-wang — APPROVED** [review]

**Pull request merged**
